version: '3.7'
services:
  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/share/nginx/html
  ubuntu:
    build: .
    container_name: ubuntuScanner
    
