FROM ubuntu:20.04
ENV DEBIAN_FRONTEND noninteractive

RUN apt update && apt-get install -y \
masscan \
net-tools
#COPY /Masscan/requirements.txt ./
#RUN pip install --no-cache-dir -r requirements.txt
#ADD python file
#CMD/RUN python file
