version: '3.7'
services:
  ubuntu:
    build: .
    container_name: ubuntuScanner
    volumes:
      - .:/code
#  web:
#    image: nginx:alpine
#    container_name: nginx
#    ports:
#      - "80:80"
#    volumes:
#      - ./website:/usr/share/nginx/html

        
